import { extractSqlVerb } from '../performance/measure.js';
import { beginOutboundSpan, endOutboundSpan, type OutboundSpanStart } from '../core/tracing.js';
import type { StackTracePlugin } from '../core/plugins/types.js';
import { safeRun } from '../core/safe-run.js';

/**
 * Knex / Lucid connection that supports the `query`, `query-response` and `query-error` events.
 */
export type LucidDatabaseLike = {
  on(event: 'query', callback: (query: unknown) => void): unknown;
  on(event: 'query-response', callback: (response: unknown, query: unknown) => void): unknown;
  on(event: 'query-error', callback: (error: unknown, query: unknown) => void): unknown;
};

/**
 * Fields knex puts on the `query` / `query-response` / `query-error` event payloads.
 * `__knexQueryUid` is the per-query id used to pair the start and completion events;
 * autogenerated notifications (e.g. mssql BEGIN/SAVE/ROLLBACK TRANSACTION) carry no uid
 * and no completion counterpart.
 */
type KnexQueryEvent = {
  __knexQueryUid?: string;
  sql?: string;
  method?: string;
};

type PendingQuerySpan = {
  begin: OutboundSpanStart;
  operationName: string;
  attributes: Record<string, unknown>;
};

/**
 * Upper bound on tracked in-flight queries. Emit paths without a completion event
 * (e.g. knex `.stream()`) must not grow the pending map forever; beyond the cap the
 * oldest entry is dropped and its span is never emitted.
 */
export const MAX_PENDING_LUCID_QUERIES = 1000;

/** Bulk insert pode ter megabytes de SQL; verbo e tabela estão sempre no começo do texto. */
const MAX_SQL_SCAN_CHARS = 8_192;

export type LucidStackTracePluginOptions = {
  /** Real database engine name, e.g. `postgres`, `mysql`, or `sqlserver`. */
  dbSystem?: string;
};

function sanitizeIdentifier(token: string | undefined): string | undefined {
  if (token === undefined) return undefined;
  const cleaned = token.replace(/[,;]/gu, '').replace(/["`[\]]/gu, '');
  const parts = cleaned
    .split('.')
    .map((part) => part.trim())
    .filter(Boolean);
  const last = parts.at(-1);
  if (last === undefined) return undefined;
  return /^[A-Za-z_][A-Za-z0-9_$]*$/u.test(last) ? last : undefined;
}

function tokenAfter(sql: string, marker: string): string | undefined {
  const normalized = sql.replace(/\s+/gu, ' ').trim();
  const index = normalized.toUpperCase().indexOf(marker);
  if (index < 0) return undefined;
  return normalized
    .slice(index + marker.length)
    .trim()
    .split(/\s+/u)[0];
}

function inferTable(sql: string | undefined, verb: string | undefined): string | undefined {
  if (sql === undefined || verb === undefined) return undefined;
  if (verb === 'SELECT') return sanitizeIdentifier(tokenAfter(sql, ' FROM '));
  if (verb === 'INSERT') return sanitizeIdentifier(tokenAfter(sql, ' INTO '));
  if (verb === 'UPDATE') return sanitizeIdentifier(tokenAfter(sql, 'UPDATE '));
  if (verb === 'DELETE') return sanitizeIdentifier(tokenAfter(sql, ' FROM '));
  if (verb === 'TRUNCATE') return sanitizeIdentifier(tokenAfter(sql, ' TABLE '));
  return undefined;
}

function inferOperationName(verb: string | undefined, table: string | undefined): string {
  const operation = (verb ?? 'QUERY').toLowerCase();
  return table !== undefined ? `Lucid.${table}.${operation}` : `Lucid.${operation}`;
}

/**
 * Emits DB spans for completed queries without sending raw SQL or bindings.
 *
 * Knex emits `query` before the statement runs and `query-response` / `query-error` after it
 * finishes; the span is the window between the paired events (matched by `__knexQueryUid`).
 */
export function createLucidStackTracePlugin(
  database: LucidDatabaseLike,
  options: LucidStackTracePluginOptions = {},
): StackTracePlugin {
  return {
    name: 'db-lucid',
    type: 'db',
    init() {
      const pending = new Map<string, PendingQuerySpan>();

      const start = (query: unknown): void => {
        const q = query as KnexQueryEvent | null | undefined;
        const uid = q?.__knexQueryUid;
        if (q === null || q === undefined || typeof uid !== 'string' || uid === '') return;
        const begin = beginOutboundSpan();
        if (begin === null) return;
        const sql = typeof q.sql === 'string' ? q.sql.slice(0, MAX_SQL_SCAN_CHARS) : undefined;
        const verb = extractSqlVerb(sql) ?? (q.method !== undefined ? q.method.toUpperCase() : undefined);
        const table = inferTable(sql, verb);
        const operationName = inferOperationName(verb, table);
        pending.set(uid, {
          begin,
          operationName,
          attributes: {
            db_system: options.dbSystem ?? 'unknown',
            db_operation: verb ?? operationName,
            ...(table !== undefined ? { db_table: table } : {}),
          },
        });
        if (pending.size > MAX_PENDING_LUCID_QUERIES) {
          const oldest = pending.keys().next().value;
          if (oldest !== undefined) pending.delete(oldest);
        }
      };

      const finish = (query: unknown, err?: Error): void => {
        const uid = (query as KnexQueryEvent | null | undefined)?.__knexQueryUid;
        if (typeof uid !== 'string') return;
        const entry = pending.get(uid);
        if (entry === undefined) return;
        pending.delete(uid);
        endOutboundSpan(entry.begin, {
          name: entry.operationName,
          type: 'db',
          attributes: entry.attributes,
          ...(err !== undefined ? { err } : {}),
        });
      };

      // O knex emite estes eventos de dentro do executor da query: um throw aqui voltaria para a query
      // do cliente. Cada listener é dono da própria falha.
      database.on('query', (query: unknown) => {
        safeRun('lucid.query', () => start(query));
      });

      database.on('query-response', (_response: unknown, query: unknown) => {
        safeRun('lucid.queryResponse', () => finish(query));
      });

      database.on('query-error', (error: unknown, query: unknown) => {
        safeRun('lucid.queryError', () => finish(query, error instanceof Error ? error : new Error(String(error))));
      });
    },
  };
}
